name: release

permissions:
  contents: write
  pull-requests: read

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main branch
        uses: actions/checkout@v4
      - name: Clone EcklerOChokola/C-Utils PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'EcklerOChokola'
          repository: 'C-Utils'
      - name: Move C-Utils to c_utils for path matching
        run: mv C-Utils c_utils
      - name: Publish tag and release
        id: create_tag_and_release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: minor
          release_name: ':rocket: Version <RELEASE_VERSION>'
